/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#7cb3ff",
        "on-primary": "#002b6b",
        "primary-container": "#1a6dff",
        "on-primary-container": "#d6e3ff",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#7cb3ff",
        "on-primary-fixed": "#001845",
        "on-primary-fixed-variant": "#0042a3",
        "inverse-primary": "#4d8aff",

        "secondary": "#ffb899",
        "on-secondary": "#5c1700",
        "secondary-container": "#ff5c2e",
        "on-secondary-container": "#fff0eb",
        "secondary-fixed": "#fff0eb",
        "secondary-fixed-dim": "#ffb899",
        "on-secondary-fixed": "#2d0a00",
        "on-secondary-fixed-variant": "#8b2500",

        "tertiary": "#56f0a0",
        "on-tertiary": "#00381e",
        "tertiary-container": "#00b360",
        "on-tertiary-container": "#c0ffda",
        "tertiary-fixed": "#c0ffda",
        "tertiary-fixed-dim": "#56f0a0",
        "on-tertiary-fixed": "#002010",
        "on-tertiary-fixed-variant": "#006b38",

        "error": "#ff7b8a",
        "on-error": "#690013",
        "error-container": "#d32030",
        "on-error-container": "#ffdad8",

        "background": "#0a0d14",
        "on-background": "#e4e6ed",
        "surface": "#0a0d14",
        "on-surface": "#e4e6ed",
        "surface-variant": "#3a3f4a",
        "on-surface-variant": "#c8ccd8",
        "inverse-surface": "#e4e6ed",
        "inverse-on-surface": "#2c2f36",
        "surface-tint": "#7cb3ff",
        "surface-dim": "#0a0d14",
        "surface-bright": "#3d4149",
        "surface-container-lowest": "#080a10",
        "surface-container-low": "#13161e",
        "surface-container": "#1a1d26",
        "surface-container-high": "#252830",
        "surface-container-highest": "#30343c",

        "outline": "#9ba0ad",
        "outline-variant": "#4a4f5c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        base: "4px",
        margin: "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      boxShadow: {
        "glow-primary": "0 0 20px rgba(124, 179, 255, 0.25)",
        "glow-error": "0 0 20px rgba(255, 123, 138, 0.25)",
        "glow-tertiary": "0 0 20px rgba(86, 240, 160, 0.25)",
        "glow-secondary": "0 0 20px rgba(255, 184, 153, 0.25)",
        "card": "0 2px 12px rgba(0, 0, 0, 0.3)",
        "card-hover": "0 4px 24px rgba(0, 0, 0, 0.4)",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-glow": "linear-gradient(135deg, rgba(124,179,255,0.08) 0%, rgba(86,240,160,0.04) 50%, rgba(255,184,153,0.06) 100%)",
      },
    },
  },
  plugins: [],
}

// tailwind.config.js
module.exports = {
  content: ["./src/**/*.{html,js,jsx,ts,tsx}"], // adjust to your project
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        secondary: 'var(--color-secondary)',
        'on-secondary': 'var(--color-on-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        tertiary: 'var(--color-tertiary)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        error: 'var(--color-error)',
        'on-error': 'var(--color-on-error)',
        'error-container': 'var(--color-error-container)',
        'on-error-container': 'var(--color-on-error-container)',
        background: 'var(--color-background)',
        'on-background': 'var(--color-on-background)',
        surface: 'var(--color-surface)',
        'on-surface': 'var(--color-on-surface)',
        'surface-variant': 'var(--color-surface-variant)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
      },
    },
  },
  plugins: [],
};